### ISSUE TITLE
cargo content aob

### ISSUE THREAD

**Issue by eidng8** [mkmark/X3-notoriety-hack#1]
Not sure what you want to do with this information, just to leave a note here.

e.g. below is the spacelab headquaters packed in ST cargo bay:

```
00 00 00 01 3e 00 05 00 01 01 00 00 00
            ----- =====    ^^^^^^^^^^^
              s     t          qty
```

where:
* `s` is the sub-type
* `t` is the type
* `qty` is the quantity

It seems to be allocated in about 0x18 byte blocks. I can't isolate more signifying adjacent bytes. However:
* one has to actually possess the ware in cargo bay before this can be actually scanned;
* the cargo is not randomly allocated, meaning that you can't change the cargo by modifying type or sub-type field, doing so will render the cargo dispear;
* since the bytes are relatively short, it's most likely to have multiple results, there won't be much though;
* also remember to add the sub-type value by `4` in order to get the correct index of txt file index;
* the quantity value can be modified safely.

**Comment by mkmark** [comment]
Very useful info, but still not enough to implement a usable script.
I myself would use [unmodifier](https://docs.google.com/document/d/1atdLILlMxCPgK1C6_Hksel4siwBFgtObtaDo2fxbkJk/view?pli=1#heading=h.9m4agj1ilk19) in case the cheat engine method gets too complicated.
