### ISSUE TITLE
ship upgrade aob

### ISSUE THREAD

**Issue by eidng8** [mkmark/X3-notoriety-hack#2]
```
02 00 00 00 01 02 00 00 00 01 02 00 00 00
-----------    ===========    ^^^^^^^^^^^
  engine          rudder         cargo
```

Please note that once changed, this sequence cannot be scanned again. If you want to find a super-tuned ship, subtract effective value by the vanilla max value.

**Comment by mkmark** [comment]
Until now the most effective way to manipulate ship upgrades is still to modify and scan.
AOB does not seem effective given no fixed neighbor values.
